name: "Send build success message to Microsoft Teams"
description: "Send message to a web hook assigned to a Microsoft Teams Channel"
author: "Mohammad Moattar"
inputs:
  webhook-url:
    description: "url of the web hook in microsoft team"
  message:
    description: "message to send to Microsoft Teams"
    default: "Build has successfully done."
runs:
  using: "node12"
  main: "lib/main.js"
